### ISSUE TITLE
Latest Master Has Breaking Diagnostic Changes

### ISSUE THREAD

**Issue by tjdevries** [weilbith/nvim-lsp-diamove#1]
Hi :) 

I changed a bunch of the interfaces on neovim master, just as a heads up.

You'll want to check out the PR: https://github.com/neovim/neovim/commit/f75be5e9d510d5369c572cf98e78d9480df3b0bb

Thanks!

**Comment by weilbith** [comment]
Thanks for leaving the note here.
And thanks for all your hard work to improve NeoVim core. :pray: 

PS: Was kinda nice to see you in the Twitch stream to open the issue here. :stuck_out_tongue_winking_eye:
